In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm 
import numpy as np
from sklearn.model_selection import train_test_split

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [0]:
data = pd.read_csv("merged_gw.csv", encoding='latin-1')

In [3]:
data.head()

                    name  assists  ...  yellow_cards  GW
0    Aaron_Cresswell_402        0  ...             0   1
1        Aaron_Lennon_83        0  ...             0   1
2         Aaron_Mooy_199        0  ...             0   1
3        Aaron_Ramsey_14        0  ...             0   1
4  Aaron_Wan-Bissaka_145        1  ...             0   1

[5 rows x 56 columns]

In [0]:
X = data.iloc[:, [1,2,3,4,7,8,9,11,14,17,19,23,29,30,36,37,41,42,54]]
Y = data.iloc[:,[18]]

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state = 0)

In [0]:
regressor = LinearRegression()

In [0]:
model = regressor.fit(X_train, y_train)

In [0]:
y_pred = regressor.predict(X_test)

In [18]:
from sklearn.metrics import mean_squared_error
from math import sqrt
rmse = sqrt(mean_squared_error(y_test, y_pred))
print(rmse)

0.6645641256805647

In [19]:
r2 = model.score(X_train, y_train)
print(r2)

0.5354796255813754

In [0]:
#import matplotlib.pyplot as plt
#plt.scatter(X_train, y_train , color = 'red')
#plt.plot(X_train, regressor.predict(X_train), color = 'blue')
#plt.title("Metrics effect on goal conceded")
#plt.xlabel("Performance Metrics")
#plt.ylabel("Goals Conceded")
#plt.show()

In [21]:
X = sm.add_constant(X)
my_model = sm.OLS(Y, X)
result = my_model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         goals_conceded   R-squared:                       0.537
Model:                            OLS   Adj. R-squared:                  0.536
Method:                 Least Squares   F-statistic:                     984.3
Date:                Sun, 03 May 2020   Prob (F-statistic):               0.00
Time:                        01:51:15   Log-Likelihood:                -16813.
No. Observations:               16173   AIC:                         3.367e+04
Df Residuals:                   16153   BIC:                         3.382e+04
Df Model:                          19
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                               0.1029      0.007     14.821      0.000       0.089       0.117
assists                            -0.0518      0.028     -1.855      0.064      -0.107       0.003
attempted_passes                    0.0553      0.002     28.008      0.000       0.051       0.059
big_chances_created                -0.0556      0.027     -2.073      0.038      -0.108      -0.003
big_chances_missed                  0.1291      0.026      4.952      0.000       0.078       0.180
clean_sheets                       -1.6310      0.019    -85.054      0.000      -1.669      -1.593
clearances_blocks_interceptions     0.0628      0.003     24.133      0.000       0.058       0.068
completed_passes                   -0.0501      0.002    -24.164      0.000      -0.054      -0.046
dribbles                            0.0249      0.009      2.867      0.004       0.008       0.042
errors_leading_to_goal              0.8729      0.073     11.897      0.000       0.729       1.017
fouls                               0.0790      0.009      9.163      0.000       0.062       0.096
goals_scored                        0.0300      0.024      1.267      0.205      -0.016       0.076
key_passes                          0.0458      0.010      4.814      0.000       0.027       0.064
offside                             0.2243      0.017     13.315      0.000       0.191       0.257
open_play_crosses                   0.0337      0.016      2.158      0.031       0.003       0.064
recoveries                          0.0686      0.003     22.907      0.000       0.063       0.074
red_cards                           0.5937      0.111      5.367      0.000       0.377       0.811
tackled                             0.0807      0.005     14.891      0.000       0.070       0.091
tackles                             0.0370      0.010      3.863      0.000       0.018       0.056
yellow_cards                        0.0668      0.025      2.645      0.008       0.017       0.116
==============================================================================
Omnibus:                     8521.287   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            86500.357
Skew:                           2.333   Prob(JB):                         0.00
Kurtosis:                      13.325   Cond. No.                         758.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.